name: Singapore
code: SG
continent: Asia
currency: SGD
threshold: 25
description: Singapore
characteristics:
  - Common law
  - Parliamentary republic
  - Financial hub
availableBusinessTypes:
  - partnership
  - individual
  - nonprofit
  - public_company
  - private_company
  - sole_proprietorship
additionalRequirements:
  - shopify_payments_kyc
  - financial_services_regulations
notes: Singapore has comprehensive business structures
