# Global Regions Configuration
# This file defines all regions and their characteristics

regions:
  # North America
  US:
    name: "United States"
    code: "US"
    continent: "North America"
    currency: "USD"
    threshold: 25
    description: "United States of America"
    characteristics:
      - "Federal system"
      - "State-level regulations"
      - "Strong financial services"
      - "Comprehensive KYC requirements"
    availableBusinessTypes:
      - corporation
      - s_corporation
      - c_corporation
      - llc
      - single_member_llc
      - partnership
      - limited_partnership
      - individual
      - sole_proprietorship
      - trust
      - cooperative
      - nonprofit
    additionalRequirements:
      - shopify_payments_kyc
      - financial_services_regulations
      - anti_money_laundering
      - data_protection
    notes: "US has comprehensive financial services regulations and KYC requirements"

  CA:
    name: "Canada"
    code: "CA"
    continent: "North America"
    currency: "CAD"
    threshold: 25
    description: "Canada"
    characteristics:
      - "Federal system"
      - "Provincial regulations"
      - "Strong financial services"
      - "Comprehensive KYC requirements"
    availableBusinessTypes:
      - corporation
      - llc
      - partnership
      - individual
      - trust
      - cooperative
      - nonprofit
    additionalRequirements:
      - shopify_payments_kyc
      - financial_services_regulations
      - anti_money_laundering
      - data_protection
    notes: "Canada has similar regulatory framework to US"

  # Europe
  UK:
    name: "United Kingdom"
    code: "UK"
    continent: "Europe"
    currency: "GBP"
    threshold: 25
    description: "United Kingdom of Great Britain and Northern Ireland"
    characteristics:
      - "Common law system"
      - "Strong financial services"
      - "EU/UK regulations"
      - "Comprehensive KYC requirements"
    availableBusinessTypes:
      - corporation
      - llc
      - partnership
      - limited_partnership
      - individual
      - trust
      - cooperative
      - nonprofit
    additionalRequirements:
      - shopify_payments_kyc
      - financial_services_regulations
      - anti_money_laundering
      - data_protection
    notes: "UK has strong financial services regulations and KYC requirements"

  EU:
    name: "European Union"
    code: "EU"
    continent: "Europe"
    currency: "EUR"
    threshold: 25
    description: "European Union member states"
    characteristics:
      - "Civil law system"
      - "EU regulations"
      - "Strong financial services"
      - "GDPR compliance"
    availableBusinessTypes:
      - corporation
      - llc
      - partnership
      - individual
      - trust
      - cooperative
      - nonprofit
    additionalRequirements:
      - shopify_payments_kyc
      - financial_services_regulations
      - anti_money_laundering
      - data_protection
    notes: "EU has comprehensive regulations including GDPR"

  # Asia Pacific
  AU:
    name: "Australia"
    code: "AU"
    continent: "Oceania"
    currency: "AUD"
    threshold: 25
    description: "Commonwealth of Australia"
    characteristics:
      - "Common law system"
      - "Strong financial services"
      - "Comprehensive regulations"
      - "KYC requirements"
    availableBusinessTypes:
      - corporation
      - llc
      - partnership
      - individual
      - trust
      - cooperative
      - nonprofit
    additionalRequirements:
      - shopify_payments_kyc
      - financial_services_regulations
      - anti_money_laundering
      - data_protection
    notes: "Australia has strong financial services regulations"

  SG:
    name: "Singapore"
    code: "SG"
    continent: "Asia"
    currency: "SGD"
    threshold: 25
    description: "Republic of Singapore"
    characteristics:
      - "Common law system"
      - "Financial hub"
      - "Strong regulations"
      - "KYC requirements"
    availableBusinessTypes:
      - corporation
      - llc
      - partnership
      - individual
      - trust
      - cooperative
      - nonprofit
    additionalRequirements:
      - shopify_payments_kyc
      - financial_services_regulations
      - anti_money_laundering
      - data_protection
    notes: "Singapore is a major financial hub with strong regulations"

  HK:
    name: "Hong Kong"
    code: "HK"
    continent: "Asia"
    currency: "HKD"
    threshold: 25
    description: "Hong Kong Special Administrative Region"
    characteristics:
      - "Common law system"
      - "Financial hub"
      - "Strong regulations"
      - "KYC requirements"
    availableBusinessTypes:
      - corporation
      - llc
      - partnership
      - individual
      - trust
      - cooperative
      - nonprofit
    additionalRequirements:
      - shopify_payments_kyc
      - financial_services_regulations
      - anti_money_laundering
      - data_protection
    notes: "Hong Kong is a major financial hub with strong regulations"

  JP:
    name: "Japan"
    code: "JP"
    continent: "Asia"
    currency: "JPY"
    threshold: 25
    description: "Japan"
    characteristics:
      - "Civil law system"
      - "Strong financial services"
      - "Comprehensive regulations"
      - "KYC requirements"
    availableBusinessTypes:
      - corporation
      - llc
      - partnership
      - individual
      - trust
      - cooperative
      - nonprofit
    additionalRequirements:
      - shopify_payments_kyc
      - financial_services_regulations
      - anti_money_laundering
      - data_protection
    notes: "Japan has comprehensive financial services regulations"

# Region Categories
categories:
  north_america:
    name: "North America"
    description: "North American countries"
    characteristics:
      - "Federal systems"
      - "Strong financial services"
      - "Comprehensive regulations"
  
  europe:
    name: "Europe"
    description: "European countries and regions"
    characteristics:
      - "Strong financial services"
      - "EU regulations"
      - "GDPR compliance"
  
  asia_pacific:
    name: "Asia Pacific"
    description: "Asia Pacific countries and regions"
    characteristics:
      - "Financial hubs"
      - "Strong regulations"
      - "KYC requirements"
  
  oceania:
    name: "Oceania"
    description: "Oceania countries"
    characteristics:
      - "Common law systems"
      - "Strong regulations"
      - "KYC requirements" 